# Generated by Django 3.2.4 on 2021-08-09 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
