# Generated by Django 3.2.4 on 2021-08-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='item',
            field=models.CharField(choices=[('people', '실존인물'), ('character', '캐릭터'), ('etc', '그외'), ('선택안함', '선택안함'), ('2D', '2D')], default='선택안함', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='twitter',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='nickname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone_num',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='profile_img',
            field=models.ImageField(blank=True, default='./static/기본이미지.jpg', null=True, upload_to='accounts/'),
        ),
    ]
