# Generated by Django 3.2 on 2021-08-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='item',
            field=models.CharField(choices=[('people', '실존인물'), ('character', '캐릭터'), ('etc', '그외'), ('2D', '2D')], max_length=80),
        ),
        migrations.AlterField(
            model_name='semigoods',
            name='item',
            field=models.CharField(choices=[('people', '실존인물'), ('character', '캐릭터'), ('etc', '그외'), ('2D', '2D')], max_length=80),
        ),
    ]
