# Generated by Django 3.2.4 on 2021-08-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='item',
            field=models.CharField(choices=[('etc', '그외'), ('character', '캐릭터'), ('2D', '2D'), ('people', '실존인물')], max_length=80),
        ),
        migrations.AlterField(
            model_name='semigoods',
            name='item',
            field=models.CharField(choices=[('etc', '그외'), ('character', '캐릭터'), ('2D', '2D'), ('people', '실존인물')], max_length=80),
        ),
    ]
