# Generated by Django 3.2.4 on 2021-08-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20210807_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='item',
            field=models.CharField(choices=[('2D', '2D'), ('people', '실존인물'), ('etc', '그외'), ('character', '캐릭터')], max_length=80),
        ),
        migrations.AlterField(
            model_name='semigoods',
            name='item',
            field=models.CharField(choices=[('2D', '2D'), ('people', '실존인물'), ('etc', '그외'), ('character', '캐릭터')], max_length=80),
        ),
    ]
