# Generated by Django 3.2 on 2021-08-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20210808_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='account_deposit',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='count',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='count_deposit',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='count_needs',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='howto_delivery',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='information_deposit',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='information_needs',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='location1',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='location2',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='term_deposit',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='term_needs',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='writer',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='goods',
            name='item',
            field=models.CharField(choices=[('etc', '그외'), ('2D', '2D'), ('people', '실존인물'), ('character', '캐릭터')], max_length=80),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='product_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='semigoods',
            name='item',
            field=models.CharField(choices=[('etc', '그외'), ('2D', '2D'), ('people', '실존인물'), ('character', '캐릭터')], max_length=80),
        ),
    ]
