# Generated by Django 3.2 on 2021-08-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20210808_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='item',
            field=models.CharField(choices=[('character', '캐릭터'), ('etc', '그외'), ('people', '실존인물'), ('2D', '2D')], max_length=80),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='product_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='semigoods',
            name='item',
            field=models.CharField(choices=[('character', '캐릭터'), ('etc', '그외'), ('people', '실존인물'), ('2D', '2D')], max_length=80),
        ),
    ]
