# Generated by Django 3.2.4 on 2021-08-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20210809_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='item',
            field=models.CharField(choices=[('character', '캐릭터'), ('people', '실존인물'), ('2D', '2D'), ('etc', '그외')], max_length=80),
        ),
        migrations.AlterField(
            model_name='semigoods',
            name='item',
            field=models.CharField(choices=[('character', '캐릭터'), ('people', '실존인물'), ('2D', '2D'), ('etc', '그외')], max_length=80),
        ),
    ]
